### ISSUE TITLE
Lire les publications dans les pages "people"

### ISSUE THREAD

**Issue by ThomasEscorne** [LnHaag/Pterosor#1]
Quand  on clique sur "Read" sur les publication d'un membre de l'équipe on est redirigé vers la page https://arxiv.org/pdf/undefined , on ne peut donc pas lire les publications

**Comment by ThomasEscorne** [comment]
(alors que ça marche très bien sur la page Publications)

**Comment by LnHaag** [comment]
Bonjour Thomas,
Merci pour cette remarque. En effet, en damandant aux interressés, les publications peuvent être archivées et retrouvées à deux endroits différents... Dans un cas, l'utilisateur ouvrira un pdf en cliquant sur le bouton, dans l'autre, un lien ( cette fois ci dans une nouvelle fenêtre) vers le site qui héberge l'article ( sur la page de l'article en question!). Le problème survient lorsque l'article est trop ancien ( il n'a pas de numéro), ou qu'il n'est pas libre de droit. Dans ce cas là, le bouton read n'aparaît pas.
J'ai donc corrigé !
